name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
api-version: 1.14

main: ${mainClass}

commands:
   boomhalt:
      description: Allows the removal of all TNT, even primed TNT.
      usage: /boomhalt

permissions:
  boomhalt:
    description: Allows the removal of all TNT, even primed TNT.
    default: op
